/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConferenteRouteImport } from './routes/conferente'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SorteadorRouteImport } from './routes/sorteador'
import { Route as ApiBingoDrawRouteImport } from './routes/api/bingo/draw'
import { Route as ApiBingoResetRouteImport } from './routes/api/bingo/reset'
import { Route as ApiBingoStateRouteImport } from './routes/api/bingo/state'
import { Route as ApiBingoStreamRouteImport } from './routes/api/bingo/stream'
import { Route as ApiBingoToggleRouteImport } from './routes/api/bingo/toggle'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConferenteRoute = ConferenteRouteImport.update({
  id: '/conferente',
  path: '/conferente',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SorteadorRoute = SorteadorRouteImport.update({
  id: '/sorteador',
  path: '/sorteador',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBingoDrawRoute = ApiBingoDrawRouteImport.update({
  id: '/api/bingo/draw',
  path: '/api/bingo/draw',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBingoResetRoute = ApiBingoResetRouteImport.update({
  id: '/api/bingo/reset',
  path: '/api/bingo/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBingoStateRoute = ApiBingoStateRouteImport.update({
  id: '/api/bingo/state',
  path: '/api/bingo/state',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBingoStreamRoute = ApiBingoStreamRouteImport.update({
  id: '/api/bingo/stream',
  path: '/api/bingo/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBingoToggleRoute = ApiBingoToggleRouteImport.update({
  id: '/api/bingo/toggle',
  path: '/api/bingo/toggle',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/conferente': typeof ConferenteRoute
  '/login': typeof LoginRoute
  '/sorteador': typeof SorteadorRoute
  '/api/bingo/draw': typeof ApiBingoDrawRoute
  '/api/bingo/reset': typeof ApiBingoResetRoute
  '/api/bingo/state': typeof ApiBingoStateRoute
  '/api/bingo/stream': typeof ApiBingoStreamRoute
  '/api/bingo/toggle': typeof ApiBingoToggleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/conferente': typeof ConferenteRoute
  '/login': typeof LoginRoute
  '/sorteador': typeof SorteadorRoute
  '/api/bingo/draw': typeof ApiBingoDrawRoute
  '/api/bingo/reset': typeof ApiBingoResetRoute
  '/api/bingo/state': typeof ApiBingoStateRoute
  '/api/bingo/stream': typeof ApiBingoStreamRoute
  '/api/bingo/toggle': typeof ApiBingoToggleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/conferente': typeof ConferenteRoute
  '/login': typeof LoginRoute
  '/sorteador': typeof SorteadorRoute
  '/api/bingo/draw': typeof ApiBingoDrawRoute
  '/api/bingo/reset': typeof ApiBingoResetRoute
  '/api/bingo/state': typeof ApiBingoStateRoute
  '/api/bingo/stream': typeof ApiBingoStreamRoute
  '/api/bingo/toggle': typeof ApiBingoToggleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/conferente'
    | '/login'
    | '/sorteador'
    | '/api/bingo/draw'
    | '/api/bingo/reset'
    | '/api/bingo/state'
    | '/api/bingo/stream'
    | '/api/bingo/toggle'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/conferente'
    | '/login'
    | '/sorteador'
    | '/api/bingo/draw'
    | '/api/bingo/reset'
    | '/api/bingo/state'
    | '/api/bingo/stream'
    | '/api/bingo/toggle'
  id:
    | '__root__'
    | '/'
    | '/conferente'
    | '/login'
    | '/sorteador'
    | '/api/bingo/draw'
    | '/api/bingo/reset'
    | '/api/bingo/state'
    | '/api/bingo/stream'
    | '/api/bingo/toggle'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConferenteRoute: typeof ConferenteRoute
  LoginRoute: typeof LoginRoute
  SorteadorRoute: typeof SorteadorRoute
  ApiBingoDrawRoute: typeof ApiBingoDrawRoute
  ApiBingoResetRoute: typeof ApiBingoResetRoute
  ApiBingoStateRoute: typeof ApiBingoStateRoute
  ApiBingoStreamRoute: typeof ApiBingoStreamRoute
  ApiBingoToggleRoute: typeof ApiBingoToggleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conferente': {
      id: '/conferente'
      path: '/conferente'
      fullPath: '/conferente'
      preLoaderRoute: typeof ConferenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sorteador': {
      id: '/sorteador'
      path: '/sorteador'
      fullPath: '/sorteador'
      preLoaderRoute: typeof SorteadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bingo/draw': {
      id: '/api/bingo/draw'
      path: '/api/bingo/draw'
      fullPath: '/api/bingo/draw'
      preLoaderRoute: typeof ApiBingoDrawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bingo/reset': {
      id: '/api/bingo/reset'
      path: '/api/bingo/reset'
      fullPath: '/api/bingo/reset'
      preLoaderRoute: typeof ApiBingoResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bingo/state': {
      id: '/api/bingo/state'
      path: '/api/bingo/state'
      fullPath: '/api/bingo/state'
      preLoaderRoute: typeof ApiBingoStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bingo/stream': {
      id: '/api/bingo/stream'
      path: '/api/bingo/stream'
      fullPath: '/api/bingo/stream'
      preLoaderRoute: typeof ApiBingoStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bingo/toggle': {
      id: '/api/bingo/toggle'
      path: '/api/bingo/toggle'
      fullPath: '/api/bingo/toggle'
      preLoaderRoute: typeof ApiBingoToggleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConferenteRoute: ConferenteRoute,
  LoginRoute: LoginRoute,
  SorteadorRoute: SorteadorRoute,
  ApiBingoDrawRoute: ApiBingoDrawRoute,
  ApiBingoResetRoute: ApiBingoResetRoute,
  ApiBingoStateRoute: ApiBingoStateRoute,
  ApiBingoStreamRoute: ApiBingoStreamRoute,
  ApiBingoToggleRoute: ApiBingoToggleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
